### ISSUE TITLE
Please upload the new typescript declarations to NPM

### ISSUE THREAD

**Issue by amiorenstx** [gkjohnson/urdf-loaders#128]
Please upload the new typescript declarations to NPM

**Comment by gkjohnson** [comment]
Hey @amiorenstx thanks for reminding me! I'll try to publish those tonight or tomorrow morning.

Can I ask what you're using the loader for? I'm always excited to hear about projects that are benefiting.

Thanks again!

**Comment by amiorenstx** [comment]
sent u a pm :)

**Comment by gkjohnson** [comment]
Just published in version 0.6.2!

Thanks again!
