### ISSUE TITLE
Licensing of URDF Loader

### ISSUE THREAD

**Issue by femtogram** [gkjohnson/urdf-loaders#145]
Hi,

I was wondering what the license situation is for this project. You have Apache 2.0 listed, but right underneath it is the Caltech copyright notice which seems to be incompatible with Apache 2.0. What is the availability of this project for commercial use?

Thanks!

**Comment by gkjohnson** [comment]
Just to keep you updated: unfortunately the appropriate people weren't available to talk but we have a meeting scheduled for next week to discuss this!

**Comment by femtogram** [comment]
Alright, understood! Thanks for keeping me in the loop!

**Comment by gkjohnson** [comment]
As you've seen I've received permission to update the copyright statement after a meeting last week and just merged it into master in #147 -- hopefully that change satisfies your needs! Thank you again for bringing this up! I'll publish a new version to npm with the updated license soon.

**Comment by gkjohnson** [comment]
@femtogram just published 0.7.2 with this change to npm if you needed it! Thank you again
