### ISSUE TITLE
Script Tag instead of NPM

### ISSUE THREAD

**Issue by kavikode** [gkjohnson/urdf-loaders#152]
Is there a script tag for the URDFLoader class instead of NPM please? I cannot find it. I tried to do the following, but it didn't work for me. Please help.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<!-- Register the Element -->
<script href=".../URDFLoader.js" ></script>
<script href=".../urdf-viewer-element.js" ></script>
<script>customElements.define('urdf-viewer', URDFViewer)</script>

<body>
<urdf-viewer package=".../package/dir/" urdf="T12/urdf/T12.URDF" up="Z+" display-shadow ambient-color="red"></urdf-viewer>
</body>
</html>
```

**Comment by gkjohnson** [comment]
The universal, script-tag-loadable variants of the classes are available in the [UMD folder](https://github.com/gkjohnson/urdf-loaders/tree/master/javascript/umd) and you should be able to load them like you've referenced in your example.
