### ISSUE TITLE
Joints Control Menu

### ISSUE THREAD

**Issue by kavikode** [gkjohnson/urdf-loaders#157]
[baxter.zip](https://github.com/gkjohnson/urdf-loaders/files/4106430/baxter.zip)
[fetch.zip](https://github.com/gkjohnson/urdf-loaders/files/4106434/fetch.zip)

![The-Pepper-robots-joints](https://user-images.githubusercontent.com/29847048/73035214-559fe900-3e15-11ea-8336-cf83e01fc793.png)
![PR2 joints](https://user-images.githubusercontent.com/29847048/73035534-66049380-3e16-11ea-8497-fd51285bd816.png)
![Baxter](https://user-images.githubusercontent.com/29847048/73037515-5b013180-3e1d-11ea-8b3f-52d19ce43414.png)
![Fetch](https://user-images.githubusercontent.com/29847048/73037534-694f4d80-3e1d-11ea-9c5e-cad4941e4f57.png)

Although the Pepper, PR2, Baxter, and Fetch models are visible now, all of the joints that have the ability to move do not appear in the joint control menu. 

Please see attached the images of the joints for each of the model and the URDF files for each model.

Can you please help me understand how I can resolve this so the joints are shown in the control menu?

http://csee.umbc.edu/~kavi1/pr2.zip
[pepper.zip](https://github.com/gkjohnson/urdf-loaders/files/4106428/pepper.zip)

**Comment by kavikode** [comment]
Many thanks in advance @gkjohnson I'm grateful

**Comment by gkjohnson** [comment]
It looks like if you add the css property `overflow:hidden` to the `#controls` menu it enables the scroll bar -- something may have changed with the flex styles at some point and broke this. Feel free to make a PR!

**Comment by kavikode** [comment]
Thanks a million @gkjohnson You are wonderful! I'll be using your repo for my research and citing your name. Hope it is okay.
