### ISSUE TITLE
Joint axes misaligned in global space

### ISSUE THREAD

**Issue by ndahn** [gkjohnson/urdf-loaders#210]
I found a very strange issue where joint axes are not aligned anymore when transformed to global space. Do you have by chance any idea where this is coming from? 

 	scene.add(robot.model);

	for (let joint of robot.arm.movable) {
		let pos = joint.getWorldPosition();
		let jglobal = joint.localToWorld(joint.axis.clone()).normalize();
		// local axis, teal, perfectly fine
		joint.add(new ArrowHelper(joint.axis, new Vector3(), 0.35, 0x00ffff));
		// global axis, pink, misaligned
		scene.add(new ArrowHelper(jglobal, pos, 5, 0xff00aa));
	}

![image](https://user-images.githubusercontent.com/41790746/120102825-25750280-c14d-11eb-98cd-92e42f050724.png)

**Comment by gkjohnson** [comment]
Hello! [Object3D.localToWorld](https://threejs.org/docs/?q=object#api/en/core/Object3D.localToWorld) will transform a _position_ from the local frame into the world frame where as the joint axis represents a direction vector. Look into [Vector3.transformDirection](https://threejs.org/docs/?q=vect#api/en/math/Vector3.transformDirection), which should do what you want:

```js
jglobal = joint.axis.clone().transformDirection( joint.matrixWorld );
```

Of course make sure `joint.matrixWorld` is up to date, as well.

**Comment by ndahn** [comment]
Ha! This is embarassing :D Thank you a lot!
