### ISSUE TITLE
clone() not work, Replication does not show    three.js

### ISSUE THREAD

**Issue by vinvin1022** [gkjohnson/urdf-loaders#221]
const loader = new URDFLoader();
### first
loader.load(
  './public/models/urdf/fanucm45/urdf/fanuc45.urdf',
  function (robot1) {
    console.log(robot1)
    const robot = robot1.clone()
    robot.scale.set(1000, 1000, 1000)
    robot.position.set(2000, 0, 2000)
    robot.rotation.set(-1.57, 0, 0)
    scene.add(robot)
  })
![1642487081(1)](https://user-images.githubusercontent.com/6983089/149882279-01fdce91-0ddc-4520-b42f-7d635d18d572.jpg)

###second
 
![1642486945(1)](https://user-images.githubusercontent.com/6983089/149882387-0230b562-4bf7-4ba4-a2d1-40046e7768d1.jpg)
![1642486985(1)](https://user-images.githubusercontent.com/6983089/149882395-5e5aa8aa-28f8-4617-8b4a-7fec9bd643ff.jpg)

**Comment by gkjohnson** [comment]
You have to wait until all the sub geometry has finished loading before cloning. Like other three.js loaders this can be tracked with a loading manager:

```js
let robot;
const manager = new LoadingManager();
manager.onLoad = () => {

 // robot is finished loading
 scene.add( robot.clone() );

};
new URDFLoader().load( './path/to/robot.urdf', result => {

  robot = result;

} );
```
