### ISSUE TITLE
Convert material colors to Linear on load

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/urdf-loaders#224]

**Comment by EzraBrooks** [comment]
What does this entail? I've attempted to upgrade my Three version as part of my usual dependency-upgrade chores and my robots' colors are very different from how they've previously looked. Does `processMaterial` just need to load the color as RGB and then invoke `convertSRGBToLinear` on it?

**Comment by EzraBrooks** [comment]
Is this worth cutting a release for, or should I implement a workaround in my application in the `loadMeshCb` for now?

**Comment by gkjohnson** [comment]
Was just getting to it 😁 Should be published in v0.10.4

**Comment by EzraBrooks** [comment]
Excellent! Thanks for being so responsive!

**Comment by EzraBrooks** [comment]
I'm still having some trouble with this, and it's very odd. If I use `npm link` to use a local copy of 0.10.4 in my project, my colors look fine. But using the package straight from the NPM registry still produces incorrect colors. I'm baffled 😕

**Comment by gkjohnson** [comment]
I would make sure v0.10.4 is actually installed. This line here is the important one for converting the colors, as well - so you can set breakpoints to make sure it's getting here when you expect:

https://github.com/gkjohnson/urdf-loaders/blob/8f4ae740a3d7e06e810208e78105bb9592d0883b/javascript/src/URDFLoader.js#L476

**Comment by EzraBrooks** [comment]
I'll check back in later today after debugging further, but my current hunch is that my application is resolving the import to the UMD version that hasn't been updated. I saw there's a ticket for removing that; is there anything blocking that change?

**Comment by gkjohnson** [comment]
You can see in the UMD module that the converSRGBToLinear conversion is there, as well, on line 897.

https://unpkg.com/browse/urdf-loader@0.10.4/umd/URDFLoader.js

> is there anything blocking that change?

It's technically a breaking change and there are still quite a few build processes that require commonjs-style imports, unfortunately. I've tried to remove UMD on some of my other projects and it's been met with complaints.

**Comment by EzraBrooks** [comment]
You're right, I was looking at the committed copy in the repo, oops. Hmm. I can definitely verify that it is v0.10.4 installed in my project, and that I can see the conversion happening as written. Breakpoints show that it is hitting those lines. Very very strange..

**Comment by gkjohnson** [comment]
Hm 🤔 without a repro I don't think I'll be able to suggest anything else.

**Comment by EzraBrooks** [comment]
Just to follow up: it was a bug in the COLLADA material declarations in the robot description from the manufacturer.
