### ISSUE TITLE
Robot not rendering in browser (typescript app)

### ISSUE THREAD

**Issue by joaopfg** [gkjohnson/urdf-loaders#225]
Hello,

I'm implementing an angular app (typescript) in which one of the components uses this package to display urdf in a browser.
The urdf is loaded in the scene object because I can see it when I do `console.log(scene)`. However it's not loaded in the browser (Google Chrome 98.0.4758.80 ). 

My browser can load other things from `Three.js`, so I'm a bit lost. Do you have some clue ? 

The code for my angular component (typescript part) is below. The html is just one line with the component tag.

```
import { Component, AfterViewInit} from '@angular/core';

import * as THREE from 'three';

import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

import URDFLoader, { URDFRobot } from 'urdf-loader';

@Component({
  selector: 'app-robot-urdf',
  templateUrl: './robot-urdf.component.html',
  styleUrls: ['./robot-urdf.component.css']
})
export class RobotUrdfComponent implements AfterViewInit {
  constructor() {}

  ngAfterViewInit(): void {
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x263238);

    const camera = new THREE.PerspectiveCamera();
    camera.position.set(10, 10, 10);
    camera.lookAt(0, 0, 0);

    const renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.outputEncoding = THREE.sRGBEncoding;
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    document.body.appendChild( renderer.domElement );

    const directionalLight = new THREE.DirectionalLight(0xffffff, 1.0);
    directionalLight.castShadow = true;
    directionalLight.shadow.mapSize.setScalar(1024);
    directionalLight.position.set(5, 30, 5);
    scene.add(directionalLight);

    const ambientLight = new THREE.AmbientLight(0xffffff, 0.2);
    scene.add(ambientLight);

    const ground = new THREE.Mesh(new THREE.PlaneBufferGeometry(), new THREE.ShadowMaterial({ opacity: 0.25 }));
    ground.rotation.x = -Math.PI / 2;
    ground.scale.setScalar(30);
    ground.receiveShadow = true;
    scene.add(ground);

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.minDistance = 4;
    controls.target.y = 1;
    controls.update();

    const manager = new THREE.LoadingManager();
    const loader = new URDFLoader( manager );
    let robot: URDFRobot;

    loader.load(
      'assets/urdf/T12/urdf/T12_flipped.URDF',                    // The path to the URDF within the package OR absolute
      result => {
        // The robot is loaded!
        robot = result;
      }
    );

    manager.onLoad = () => {

        robot.rotation.x = Math.PI / 2;
        robot.traverse(c => {
            c.castShadow = true;
        });
        for (let i = 1; i <= 6; i++) {

            robot.joints[`HP${ i }`].setJointValue(THREE.MathUtils.degToRad(30));
            robot.joints[`KP${ i }`].setJointValue(THREE.MathUtils.degToRad(120));
            robot.joints[`AP${ i }`].setJointValue(THREE.MathUtils.degToRad(-60));

        }
        robot.updateMatrixWorld(true);

        const bb = new THREE.Box3();
        bb.setFromObject(robot);

        robot.position.y -= bb.min.y;

        scene.add(robot);

    };

    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.setPixelRatio(window.devicePixelRatio);

    camera.aspect = window.innerWidth / window.innerHeight;
    camera.updateProjectionMatrix();

    console.log(scene);
    renderer.render(scene, camera);
  }
}

```

**Comment by gkjohnson** [comment]
A live demo would be helpful here but I would make sure that there are no errors in the console indicating that geometry couldn't be loaded and that the position of the URDF model is not set to some unreasonable location. Which URDF are you loading? Does it load if you drag and drop the folder into the live viewer?

https://gkjohnson.github.io/urdf-loaders/javascript/example/bundle/index.html

**Comment by joaopfg** [comment]
@gkjohnson Hello, I'm loading a urdf from the urdf folder of this package. In fact, the code I posted in my previous message is almost identical to the `example.src.simple.js` of this package.

Here is a running example: https://stackblitz.com/edit/angular-grl1h8?file=src/app/app.component.ts

However, to reproduce it, you have to download the project and create an `assets` folder with the `urdf` folder from this project inside.

**Comment by gkjohnson** [comment]
It looks like you have no render loop. You need to rerender the scene once the model is loaded for it to show.

If you have any other general three.js questions please direct them to the three.js forums:

https://discourse.threejs.org/

**Comment by joaopfg** [comment]
Thanks, @gkjohnson . I begin experimenting with `three.js` today, so complete newbie :)
I will try to write the render loop.

However, I can render other objects from `three.js` without the render loop (for example, the first example of the manual: https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene). Is the need of a render loop a special need for objects loaded with `urdf-loaders` package ?

**Comment by gkjohnson** [comment]
Like all three.js loaders the model is loaded asynchronously so it is not immediately available after calling load.

Unfortunately I don't have the bandwidth to provide personal help for general three.js topics. Again please use the three.js forum or discord for help if you need more direction for three.js.
