### ISSUE TITLE
Cloning a URDFRobot results in mimic joints that still point to the original object

### ISSUE THREAD

**Issue by EzraBrooks** [gkjohnson/urdf-loaders#229]
We've got an application where we load a robot's URDF and then clone it for use in some motion preview features. However, we've found that if you `setJointValue` on a joint in the clone that has mimic joints, its mimics move in the original object but not the clone.

**Comment by gkjohnson** [comment]
Thanks for the report! Would you like to make a PR with a fix for the problem as well as a new test or two?

**Comment by EzraBrooks** [comment]
I'll take a stab at it; I'm departing on vacation this evening, but I'll see if I can get a PR in sometime next week.

**Comment by EzraBrooks** [comment]
we have a workaround for this issue (loading the robot twice) that's not ideal but is keeping us going for now. I will try to circle back to this when I get a chance, but currently have a bunch of non-3D-related issues on my plate for our next few sprints 😄
