### ISSUE TITLE
Is there a lightweight way to deploy client-side without NPM/Node/All The External dependencies?

### ISSUE THREAD

**Issue by slamjammin** [gkjohnson/urdf-loaders#246]
Sorry this may be an amateurish question - I am not super familiar with npm/node. I would love to implement this into a robotics dev workflow I am starting up, but trying to keep external dependencies as light as possible and use this entirely as a client side library. Is that something that is feasible?

**Comment by gkjohnson** [comment]
Yes the project is intended to be used as an external library with minimal dependencies and published to npm: https://www.npmjs.com/package/urdf-loader.

Unfortunately I can't provide of overview of modern web development and how to use npm / node here - there should be a lot of online resources on the topic, though.
