### ISSUE TITLE
How to deal with Link with Obj & MTL?

### ISSUE THREAD

**Issue by WenqiangX** [gkjohnson/urdf-loaders#248]
Hi,

My urdf's links are associated with several .obj files with mtl.
The default urdf loader can handle obj loading, but cannot import the mtl files and the textures.

Is there a quick fix for this?

Thanks!

**Comment by gkjohnson** [comment]
You can override the [mesh loading callback](https://github.com/gkjohnson/urdf-loaders/tree/master/javascript#loadMeshCb) to load the obj file along with the associated mtl files if you'd like.
