### ISSUE TITLE
Supply URDF in zip file

### ISSUE THREAD

**Issue by cognmbs** [gkjohnson/urdf-loaders#251]
Is there any way how we can provide zip file to the library?
Our limitation is that we keep zipped urdf files in backend.
Thanks.

**Comment by gkjohnson** [comment]
Hello! Yes it is possible using the capability of [LoadingManager.setURLModifier](https://threejs.org/docs/?q=LoadingM#api/en/loaders/managers/LoadingManager.setURLModifier) to swap geometry files URLs out for Object URLs that load the contents of the zip: https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL.

It's non trivial and I can't provide a full example but it should be similar to loading any three.js model from a zip file. You could try asking how to do that at the three.js forum: https://discourse.threejs.org/
