### ISSUE TITLE
Console warning is emitted every time you try to set a mimic joint's values

### ISSUE THREAD

**Issue by EzraBrooks** [gkjohnson/urdf-loaders#252]
There are a number of systems and drivers that emit mimic joints' values, even though they are unnecessary, and there are even some systems that don't support mimic joints at all (like, last I checked, NVIDIA Isaac Sim) which make publishing the mimic joint status necessary.

As a result, the software I work on publishes mimic joints values, deliberately. Unfortunately with urdf-loaders this floods the console with warnings! Would it be okay if I submitted a PR to remove this `console.warn` call?

**Comment by gkjohnson** [comment]
Yup! Makes sense -- feel free to make a PR.
