### ISSUE TITLE
Joint selection KO

### ISSUE THREAD

**Issue by yvanblanchard** [gkjohnson/urdf-loaders#257]
Hello,

After loading a URDF of robot, the joint "_a4" seems to be always selected (stays in selection/jog mode), whatever the joint selected by left-click in viewer.

![image](https://user-images.githubusercontent.com/63931618/230783954-529d1b9e-c677-4f0d-b27f-a1b1986f2f06.png)

Here is the link of urdf model:
[lbr_iiwa_14_r820-URDF.zip](https://github.com/gkjohnson/urdf-loaders/files/11185832/lbr_iiwa_14_r820-URDF.zip)

**Comment by gkjohnson** [comment]
I'm seeing these errors on the page. Similar to #256 - updating the three.js version to the latest one may fix the issue:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/734200/232025212-5f7fddf6-885c-499f-8e6e-7ee99fec3a25.png">
