### ISSUE TITLE
TS return type for setJointValue

### ISSUE THREAD

**Issue by artificial-jon** [gkjohnson/urdf-loaders#260]
In URDFClasses.d.ts, the various functions for setting joint values are defined with a void return type.  Should they not be defined to return a boolean indicating if a successful joint value update occurred or not?  All of the underlying implementation code appears to return such values already.

**Current:**
URDFJoint
    setJointValue(value0: Number, value1?: Number, value2?: Number): void;
URDFRobot
    setJointValue(jointName: String, value0: Number, value1?: Number, value2?: Number): void;
    setJointValues(values: { [ key: string ]: Number | Number[] }): void;

**Proposed:**
URDFJoint
    setJointValue(value0: Number, value1?: Number, value2?: Number): **_boolean_**;
URDFRobot
    setJointValue(jointName: String, value0: Number, value1?: Number, value2?: Number): **_boolean_**;
    setJointValues(values: { [ key: string ]: Number | Number[] }): **_boolean_**;

**Comment by gkjohnson** [comment]
Hello! Good catch - feel free to make a PR that addresses the types issue and we can get it merged

**Comment by artificial-jon** [comment]
https://github.com/gkjohnson/urdf-loaders/pull/261

**Comment by artificial-jon** [comment]
Thank you for creating this library, btw.  If you are interested, I can give you a demonstration of a pretty complicated application that leverages your URDF library some time.

**Comment by gkjohnson** [comment]
> Thank you for creating this library, btw. If you are interested, I can give you a demonstration of a pretty complicated application that leverages your URDF library some time.

Just seeing this - that would be great! I love seeing work that takes advantage of these projects - feel free to reach out over email
