### ISSUE TITLE
Zoom issue with urdf model

### ISSUE THREAD

**Issue by yvanblanchard** [gkjohnson/urdf-loaders#266]
Hello,

I face troubles when trying to zoom using mouse (middle button / wheel) with this model. I can't see the whole scene. It works fine using default example model.
I am using the online viewer on Chrome browser (drag and drop both urdf file with STL folder).

[robot-test-urdf.zip](https://github.com/gkjohnson/urdf-loaders/files/11472869/robot-test-urdf.zip)

![image](https://github.com/gkjohnson/urdf-loaders/assets/63931618/3b827a6b-f10e-469c-af40-fa429d78bb08)

**Comment by gkjohnson** [comment]
The model you've provided is thousands of meters large.

**Comment by yvanblanchard** [comment]
My bad ! the STL files were in mm
Thanks a lot

![image](https://github.com/gkjohnson/urdf-loaders/assets/63931618/68830c68-6beb-4bc1-89ac-dd7025fecd9a)
