### ISSUE TITLE
Display of fixed joints in controls 

### ISSUE THREAD

**Issue by yvanblanchard** [gkjohnson/urdf-loaders#268]
Hello,

It seems that the URDF loader displays the fixed joints in controls tree (on the left)
Is it possible to toggle off those joints, or only display the 'commanded' joints (revolute, prismatic,..) ?

Thank you

![image](https://github.com/gkjohnson/urdf-loaders/assets/63931618/f3f4cc35-7b90-4810-84c0-e2dec9ae1d18)

**Comment by gkjohnson** [comment]
Feel free to make a pull request with a toggle for displaying fixed joints.
