### ISSUE TITLE
Question of integrating ROS data with URDF…

### ISSUE THREAD

**Issue by DiosVan** [gkjohnson/urdf-loaders#269]
Hello, thank you for providing such an excellent package. I have a question regarding integrating ROS data with URDF to visualize motion simulation. After loading the URDF, I have a dataset in the format [timestamp, LINK POSITION (VECTOR3), LINK ROTATION (Euler angles)]. I would like to read this data and apply the corresponding translations and rotations to each link to visualize the motion of the actual robot. Some components have both rotational and translational motion data. While I can retrieve rotation data using the joint.setJointValue API you provided, I'm unsure how to handle the translational information. It seems that I cannot set the position of URDF joints or links. Could you provide some suggestions? Thank you very much.

**Comment by gkjohnson** [comment]
Hello! The /tf and /tf_static broadcasting system in ROS is fairly complex and requires handling transforms relative to parent frames with time dependencies. Unfortunately I don't have the bandwidth to elucidate the details of the system but you can get access to the named frames in the system to apply the position and rotation information via the [frames field](https://github.com/gkjohnson/urdf-loaders/tree/master/javascript#frames). You'll have to have a have an understanding of 3d transform matrices, three.js' Matrix4 class, and three.js' transform hierarchy to apply the transform information from there.
