### ISSUE TITLE
THREE.ColladaLoader: Unsupported primitive type:  polygons

### ISSUE THREAD

**Issue by Jayce-liang** [gkjohnson/urdf-loaders#273]
hey,there. is there hava any way to fix it?

![image](https://github.com/gkjohnson/urdf-loaders/assets/76100439/417c3150-8011-45bb-b530-1743e2e4de5e)

**Comment by gkjohnson** [comment]
The ColladaLoader is maintained in the [mrdoob/three.js](https://github.com/mrdoob/three.js/) repository - please report there.
