### ISSUE TITLE
Is it possible to change Robot Mesh Color programmatically ??

### ISSUE THREAD

**Issue by notalfredo** [gkjohnson/urdf-loaders#275]
Howdy ! I was wondering if its possible to change the color of the mesh of a robot programmatically.

Originally I tired to change the transparency but I had trouble doing that, so I decided to just try to change the color to "simplify" the problem. I feel like it should be possible since in the demo provided in the repo when I hover over a joint it changes the color. I tired to look at the source code to help me understand what I need to do but im still stuck on this problem. 

I tried something like the following 
```js
loader.load(
  "path to urdf",
  (robot) => {
     //tried to access robots properties here to try to change meshes
  }
)
```

**Comment by gkjohnson** [comment]
The robot is a THREE.Object3D so you can [traverse](https://threejs.org/docs/?q=object#api/en/core/Object3D.traverse) it and modify materials using basic three.js functions once the model is completely loaded. To determine when the model has finished loading all meshes completely you can use the three.js loading manager:

https://threejs.org/docs/?q=Loadingma#api/en/loaders/managers/LoadingManager
