### ISSUE TITLE
The robot arm renders an error in the browser

### ISSUE THREAD

**Issue by chengSenLong** [gkjohnson/urdf-loaders#284]
Hello,
I'm implementing an react app in which one of the components uses this package to display urdf in a browser.
When I want to render urdf into the scene, an error occurs
I'm a bit lost. Please help me take a look.Thanks
My react component code, error code location and error message are as follows

<img width="1920" alt="微信图片_20240312150958" src="https://github.com/gkjohnson/urdf-loaders/assets/103735488/83908161-e60e-4e17-8b7a-8575f2664203">
<img width="1920" alt="微信图片_20240312151007" src="https://github.com/gkjohnson/urdf-loaders/assets/103735488/46f459ee-dbc6-45aa-abdf-50f09c7bb70b">
<img width="949" alt="微信图片_20240312151013" src="https://github.com/gkjohnson/urdf-loaders/assets/103735488/61574578-bfbb-4bbc-bf9f-5119f472c98a">
<img width="776" alt="微信图片_20240312151020" src="https://github.com/gkjohnson/urdf-loaders/assets/103735488/a79dba71-3e3b-44b9-ac87-14173b4093fe">

**Comment by chengSenLong** [comment]
Oh, sorry. I found that the file path of urdf was wrong. It should be placed under public. This problem has been solved.

Next I will try to control the echo and delivery of the robot arm joints. 

Thanks for your help.

**Comment by gkjohnson** [comment]
If you have a new problem please open a new issue with a working demonstration of what's happening.
