### ISSUE TITLE
Add support for meshes that are distributed over multiple packages

### ISSUE THREAD

**Issue by ipa-jfh** [gkjohnson/urdf-loaders#43]
One feature that I would require is to find the meshes for an URDF in more than one ROS package, for the case that the robot description is distributed over multiple packages. 

My idea is to list the required packages in a _.rosinstall_ file ([example](https://github.com/oceansystemslab/rosinstall/blob/master/kinetic.rosinstall)), parse this from the URDF loader and then replace the  `<mesh filename="package://..." />` with the respective link from the list. 
I was thinking of the _.rosinstall_ format because I want to link to github repositories (and not to local packages of the pc).

I suppose to implement this feature optionally, so one skip the mentioned list-file if only one package is required. 

@gkjohnson What do you think of this feature?

**Comment by gkjohnson** [comment]
I'm less familiar with the intracacies of ROS, so I might need a bit more detail on this. Do you have an example URDF file that imports meshes from other ROS packages so I can get a better idea of what's needed?

From what I can glean from [here](http://docs.ros.org/independent/api/rosinstall/html/rosinstall_file_format.html), the `rosinstall` file defines where to pull remote packages from to install into your ROS environment, is that right? Is `local-name` _always_ synonymous with the package name defined in the `package.xml` file that ROS uses to name and find packages ([here](https://github.com/oceansystemslab/vehicle_interface/blob/master/package.xml))?

If this is a common / supported use case in ROS then it seems reasonable to support here! I just want to understand the use case a bit more.

Thanks!

**Comment by ipa-jfh** [comment]
Thank you for the quick reply.

> Do you have an example URDF file that imports meshes from other ROS packages so I can get a better idea of what's needed?

In ROS every package should be as fine grain as possible. So it might even be the case that the mesh/xacro of a camera will be in a dedicated ROS package.

Or another usecase is if you want to include a manipulator into a specific robot-cell. In this example the application xacro includes the robot, the tool and the robot cell. All located in a dedicated package.

```
<xacro:include filename="$(find abb_irb1200_support)/urdf/irb1200_5_90_macro.xacro"/>
<xacro:include filename="$(find blending_end_effector)/urdf/blending_eff_macro.xacro"/>
<xacro:include filename="$(find godel_irb1200_support)/urdf/automate_demo_cell_macro.xacro"/>
```

https://github.com/ros-industrial-consortium/godel/blob/kinetic-devel/godel_robots/abb/godel_irb1200/godel_irb1200_support/urdf/irb1200_workspace.xacro

> From what I can glean from here, the rosinstall file defines where to pull remote packages from to install into your ROS environment, is that right?

The rosinstall file is used to pull automatically with `wstool` a list of packages, that is right. In my case I just want to take the format of the file but use it differently. I would like to use/access the meshes remotely via CORS from their Github repos. Therefore I use the list-file as a lookup to find the github links that correspond to a certain mesh-package. 
(Later on I could imagine a script that finds all required packages by parsing an URDF and somehow also their corresponding Github repositories and creates the list-file automatically)

> Is local-name always synonymous with the package name defined in the package.xml file that ROS uses to name and find packages (here)?

What do you mean by `local-name`? 
In your use case you do not use CORS to load meshes but you have everything hosted within one repository. In this case I do not have a solution, for the case that someone would like to link to external packages.

**Comment by gkjohnson** [comment]
> What do you mean by `local-name`?

The `.rosinstall` file provides a `local-name` and a git repository so I assume the local-name corresponds to the package name? So the line

```
- git: {local-name: vehicle_interface, uri: 'git@github.com:oceansystemslab/vehicle_interface.git', version: master}
```

describes where to get files for the package named `vehicle_interface`, is that right? I was just wondering if the `local-name` in that line would _always_ correspond to the name in the [`package.xml`](https://github.com/oceansystemslab/vehicle_interface/blob/master/package.xml) in the same package.

So if you have two meshes from different packages, you would want to resolve the `package://<name>/` prefix to different locations:

`package://vehicle_interface/path/to/mesh.stl` => `https://github.com/oceansystemslab/vehicle_interface/path/to/mesh.stl`

and 

`package://nessie/path/to/other/mesh.stl` => `https://github.com/oceansystemslab/nessie/path/to/other/mesh.stl`

Am I understanding right? I have a couple ideas on how we can do which I should be able to type up later today!

Thanks for the clarification!

**Comment by ipa-jfh** [comment]
> describes where to get files for the package named vehicle_interface, is that right?

It is easier than this. With _wstool_ one can download all listed repos. `local-name` is an arbitrary name which will be used for the downloaded repo's folder name/path. Usually, one chooses the same name as the repo's name. 

> I was just wondering if the local-name in that line would always correspond to the name in the package.xml in the same package.

This must not be. 

> So if you have two meshes from different packages, you would want to resolve the package://<name>/ prefix to different locations:

Yes this is correct :)

---

Now I recognised an issue for my solution. It is not enough to link to a Github repo, because often one repo contains multiple ROS packages.

One would need to link every ROS package explicitly. 
E.g. `package://abb_irb1200_support ` => `https://github.com/ros-industrial-consortium/godel/tree/kinetic-devel/godel_robots/abb/godel_irb1200/abb_irb1200_support`
(So in this case `/godel_robots/abb/godel_irb1200/abb_irb1200_support` would need to be appended )

This would still be easy to set-up, but it would not follow the format of the `.rosinstall` file anymore.
It is actually not important to follow its format but it would have been nice if one would not need to create a new file format.

**Comment by gkjohnson** [comment]
> How about if you allow two options for your parameter package(example)

That's more or less what I was thinking. I noticed that there are `mesh://` and `package://` prefixes -- are those important to differentiate?

For the URDFLoader API I think we can can allow for providing a list of packages, like you mentioned. But I'd like a way to provide a "default" for the package:// prefix the way it works now, which this doesn't necessarily afford:

```js
loader.load({
  "vehicle_interface": "../vehicle_interface",
  "godel_irb1200": "../godel_irb1200",
}, ".../path/to/urdf.urdf", ...)
```

OR we could allow specifying the full package:// prefix, which allows us to provide the default replacement for "package://" the way it behaves now:

```js
loader.load({
  "package://vehicle_interface": "../vehicle_interface",
  "package://godel_irb1200": "../godel_irb1200",
  "package://": "../default/package/path"
}, ".../path/to/urdf.urdf", ...)
```

The package map could also go in the options:

```js
loader.load(
    "../default/package/path",
    ".../path/to/urdf.urdf",
    ...,
    {
        packageMap: {
            "vehicle_interface": "../vehicle_interface",
            "godel_irb1200": "../godel_irb1200",
        }
    })
```

I'll have to think about how to provide the element with multiple package locations in the element attribute because putting the full json object in the attribute seems a little excessive, but maybe it's unavoidable.

What are your thoughts?

**Comment by ipa-jfh** [comment]
Thank you for your ideas!

> I noticed that there are mesh:// and package:// prefixes -- are those important to differentiate?

I have not seen the `mesh://` tag in use. Do you have an example? As of right now I would vote for not supporting this tag.

> But I'd like a way to provide a "default" for the package:// prefix the way it works now, which this doesn't necessarily afford:

I would also prefer `package://` to be the _default prefix_, or as said before to not support `mesh://`.

I am a bit confused by _default prefix_ and _default package path_. 

> loader.load(
>     "../default/package/path",
>     ".../path/to/urdf.urdf",
>     ...,
>     {
>         packageMap: {
>             "vehicle_interface": "../vehicle_interface",
>             "godel_irb1200": "../godel_irb1200",
>         }
>     })

By _default package path_ you mean a package that would be used as a fallback if the name is not defined in the _packageMap_? I would prefer not to have an aditional argument like the _packageMap_.

I would vote for your first solution:

```
loader.load({
  "package1": "../path_to_package1",
  "package2": "../path_to_package2",
}, ".../path/to/urdf.urdf", ...)
```

with the possibility that one could use it still the old way (if all meshes are within one package):

```
loader.load("../path_to_package", ".../path/to/urdf.urdf", ...)
```

So the loader would detect if the argument is a `dict` or a `string`.

Thus I would prefer your option 1. But your option 2 with the defined prefixes is acceptable as well.

> I'll have to think about how to provide the element with multiple package locations in the element attribute because putting the full json object in the attribute seems a little excessive, but maybe it's unavoidable.

You mean how to pass the dict/json argument to your web component? I think it would be ok the way we sketched it above.

**Comment by gkjohnson** [comment]
> I have not seen the mesh:// tag in use. Do you have an example? As of right now I would vote for not supporting this tag.

You're right, I was recalling something else; it looks like that isn't used.

> By default package path you mean a package that would be used as a fallback if the name is not defined in the packageMap?

Sorry for the confusion. Yeah, I just mean the current behavior where `package://` is replaced with the provided path.

I don't really like the extra option, either so I'm in agreement with you. Here's what I'm thinking:

- A string _or_ object can be passed in as the package argument (as you mentioned)
- The package names in the object argument can optionally have the `package://` prefix:
```js
// both are okay
{
  "package://package1": "../path_to_package1",
  "package2": "../path_to_package2",
}
```
- The web component can take a simplified package list attribute
```html
<urdf-viewer package="package1:../path/to/package, package2:../path/to/package" ...></urdf-viewer>
```
or can be set via javascript with an object
```js
el.package = { package1: "...", package2: "..." }
```

How does that sound?

**Comment by ipa-jfh** [comment]
Yes I agree, that sounds good. 
I would have some time to implement this feature, if this is ok?

**Comment by gkjohnson** [comment]
That would be great, thanks!

**Comment by gkjohnson** [comment]
> However, I prefer the object more than the string list.

I missed this part earlier. What's the reason you prefer the object in the element attribute? I think this is where html attributes start to break down a bit and having an object defined in the attribute field can be a bit harder to read. I think the biggest thing to keep in mind is that you can't use quotes directly when typing data into an html attribute, so you'd need to use single quotes. I could go either way on it, though.

**Comment by gkjohnson** [comment]
Added in https://github.com/gkjohnson/urdf-loaders/pull/53
