### ISSUE TITLE
HTMLElement: Auto centering can cause model to bounce

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/urdf-loaders#44]
Updating the camera focus based on the robot bounding box can cause the model to move up and down too much. See line https://github.com/gkjohnson/urdf-loaders/commit/63f599a78646ee464b2e3103739308459dd3aab6#diff-2a12f3714b8acb49f99007cc2a720c89R238.

#### Possible Solutions
- Average out the center of the bounding box over multiple frames
- Interpolate to the center so it's less notice-able
- Add an attribute to enable / disable the feature

**Comment by ipa-jfh** [comment]
> If disabled in this case, would you just expect it to center about world 0, 0, 0?

I do favour that the viewer initially detects the robot's bounding box and sets centre and focus automatically. 
Maybe you could also provide a function for this, so that I can centre the viewer at certain point of time, when e.g. the first frame of the animation has been loaded

**Comment by gkjohnson** [comment]
Fixed in #70
